export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const OPEN_PURCHASABLE = "OPEN_PURCHASABLE";


export const STATE_RESET = "STATE_RESET";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const FAILED_ORDERS = "FAILED_ORDERS";


export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";